---
- name: Configure l'environnement pour WordPress
  hosts: proxmox-node
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache and required packages
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - php
          - php-mysql
          - php-xml
          - php-gd
          - php-mbstring
          - unzip
        state: present

    - name: Install MariaDB
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    - name: Create MySQL database for WordPress
      mysql_db:
        name: wordpress
        state: present

    - name: Create MySQL user for WordPress
      mysql_user:
        name: wordpressuser
        password: wordpresspassword
        priv: "wordpress.*:ALL"
        state: present

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership for WordPress files
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure WordPress database settings
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Enable and restart Apache
      service:
        name: apache2